# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab6869d05b5e34ebb6f1a25c8dbb04a58732637ed369211a6caa14f28edf9df942774af5908f5ba04c64db89016f72f0ee1d0573c0ddf878816ad9715c2ac8b6

test:
  secret_key_base: 1e613a322cc38ae5aa165a04a903c5dd94001c75b3caba6d81f632d8f97d812f9164ed40bbc1fe61fa02e7c30ba2a8db0770784c29b22bd8c3f36ff0af1a9411

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
